name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.11.0
      - name: Format Check
        run: zig fmt --check $(git ls-files '*.zig')
      - name: Build Examples
        run: |
          for build in $(git ls-files 'build.zig'); do
            dir=$(dirname $build)
            (cd $dir && zig build)
          done
